# Generated by Django 3.2.22 on 2024-03-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='recipes.Post'),
        ),
    ]
