# Generated by Django 3.2.22 on 2023-10-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20231029_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='recipes.Post'),
        ),
    ]
