# Generated by Django 3.2.22 on 2023-10-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_profile_liked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='users_who_liked', to='recipes.Post'),
        ),
    ]
