# Generated by Django 3.2.22 on 2023-10-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_profile_liked_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_posts', to='recipes.Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='recipes.Post'),
        ),
    ]
