# Generated by Django 3.2.22 on 2023-10-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20231029_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked_posts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='saved_posts',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
