# Generated by Django 3.2.22 on 2023-12-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='recipes.Post'),
        ),
    ]
